"""001 initial schema

Revision ID: 2599d104a7ce
Revises: 
Create Date: 2026-03-09 11:08:32.120850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2599d104a7ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_regime',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('regime', sa.String(length=30), nullable=False),
    sa.Column('stance', sa.String(length=20), nullable=False),
    sa.Column('sector_biases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('key_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('performance_reports',
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('portfolio_return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('benchmark_ticker', sa.String(length=20), server_default='SPY', nullable=False),
    sa.Column('alpha', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), server_default='0', nullable=False),
    sa.Column('winning_trades', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losing_trades', sa.Integer(), server_default='0', nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_win_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_loss_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('agent_accuracy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', 'period_type', name='uq_performance_reports_period')
    )
    op.create_index(op.f('ix_performance_reports_period_type'), 'performance_reports', ['period_type'], unique=False)
    op.create_table('risk_reports',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_exposure', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_positions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sector_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concentration_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('asset_type', sa.String(length=20), server_default='stock', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stocks_asset_type', 'stocks', ['asset_type'], unique=False)
    op.create_index(op.f('ix_stocks_sector'), 'stocks', ['sector'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('agent_logs',
    sa.Column('stock_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_type'), 'agent_logs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_logs_created_at'), 'agent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_logs_run_id'), 'agent_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_stock_id'), 'agent_logs', ['stock_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'period', name='uq_fundamentals_stock_period')
    )
    op.create_table('indicators',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', 'timeframe', 'indicator_name', name='uq_indicators_stock_date_tf_name')
    )
    op.create_index(op.f('ix_indicators_indicator_name'), 'indicators', ['indicator_name'], unique=False)
    op.create_table('news',
    sa.Column('stock_id', sa.UUID(), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_source'), 'news', ['source'], unique=False)
    op.create_index(op.f('ix_news_stock_id'), 'news', ['stock_id'], unique=False)
    op.create_table('prices',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', 'timeframe', name='uq_prices_stock_date_tf')
    )
    op.create_index(op.f('ix_prices_date'), 'prices', ['date'], unique=False)
    op.create_table('recommendations',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('combined_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fundamental_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_date'), 'recommendations', ['date'], unique=False)
    op.create_index(op.f('ix_recommendations_is_active'), 'recommendations', ['is_active'], unique=False)
    op.create_index(op.f('ix_recommendations_signal'), 'recommendations', ['signal'], unique=False)
    op.create_index(op.f('ix_recommendations_stock_id'), 'recommendations', ['stock_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('screening_criteria', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_is_active'), 'watchlists', ['is_active'], unique=False)
    op.create_index(op.f('ix_watchlists_stock_id'), 'watchlists', ['stock_id'], unique=False)
    op.create_table('orders',
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('ibkr_order_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('filled_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('bracket_parent_id', sa.UUID(), nullable=True),
    sa.Column('bracket_role', sa.String(length=20), nullable=True),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bracket_parent_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_bracket_parent_id'), 'orders', ['bracket_parent_id'], unique=False)
    op.create_index(op.f('ix_orders_ibkr_order_id'), 'orders', ['ibkr_order_id'], unique=False)
    op.create_index(op.f('ix_orders_recommendation_id'), 'orders', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_stock_id'), 'orders', ['stock_id'], unique=False)
    op.create_table('portfolio',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('shares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_entry_date'), 'portfolio', ['entry_date'], unique=False)
    op.create_index(op.f('ix_portfolio_status'), 'portfolio', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_stock_id'), 'portfolio', ['stock_id'], unique=False)
    op.create_table('trade_outcomes',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('actual_return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('actual_return_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('hit_target', sa.Boolean(), nullable=True),
    sa.Column('hit_stop', sa.Boolean(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_trade_outcomes_exit_date'), 'trade_outcomes', ['exit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_outcomes_exit_date'), table_name='trade_outcomes')
    op.drop_table('trade_outcomes')
    op.drop_index(op.f('ix_portfolio_stock_id'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_status'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_entry_date'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_orders_stock_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_recommendation_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_ibkr_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_bracket_parent_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_watchlists_stock_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_is_active'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_recommendations_stock_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_signal'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_is_active'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_date'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_prices_date'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_news_stock_id'), table_name='news')
    op.drop_index(op.f('ix_news_source'), table_name='news')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_indicators_indicator_name'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_agent_logs_stock_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_run_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_created_at'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_type'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector'), table_name='stocks')
    op.drop_index('ix_stocks_asset_type', table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('risk_reports')
    op.drop_index(op.f('ix_performance_reports_period_type'), table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_table('market_regime')
    # ### end Alembic commands ###
